aqm_ver: "v7.0.8"
PACKAGEHOME: "/path/to/package"
NET: "aqm"
RUN: "aqm"
PROJ: "AQM"
PROJENVIR: "DEV"
MACHINE_SITE: "development"
ENVIR: "prod"
QUEUE: "dev"
QUEUE_ARCH: "dev_transfer"
OUTPUTDIR: "/path/to/output"